#markdown: rdiscount
permalink: /:title/
url: https://fmzhao.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 50
paginate_path: "page:num"
name: 麦羞 
description: :))) | Talk is so cheap, show me the code.
author: fengmengzhao
email: fengmengzhao@gmail.com
duoshuo: fmz
weibo: 1911291317 
hub: fmzhao 
safe: false
about: "留余"
